### ISSUE TITLE
run autodock failed

### ISSUE THREAD

**Issue by drc11** [lmdu/dockey#11]
Traceback (most recent call last):
  File "MolKit\hydrogenBuilder.py", line 65, in addHydrogens
  File "MolKit\molecule.py", line 102, in __getattr__
  File "MolKit\tree.py", line 496, in __getattr__
  File "MolKit\listSet.py", line 170, in __getattr__
  File "MolKit\molecule.py", line 366, in __getattr__
AttributeError: member babel_type not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "process.py", line 318, in run
  File "process.py", line 481, in do
  File "process.py", line 279, in prepare_receptor
  File "prepare.py", line 204, in prepare_autodock_receptor
  File "AutoDockTools\MoleculePreparation.py", line 570, in __init__
  File "AutoDockTools\MoleculePreparation.py", line 140, in __init__
  File "AutoDockTools\MoleculePreparation.py", line 190, in repairMol
  File "AutoDockTools\MoleculePreparation.py", line 203, in addHydrogens
  File "MolKit\hydrogenBuilder.py", line 69, in addHydrogens
  File "PyBabel\atomTypes.py", line 141, in assignHybridization
  File "PyBabel\atomTypes.py", line 294, in valence_two
  File "PyBabel\util.py", line 55, in bond_angle
ZeroDivisionError: ('Input used:', [15.352, 38.929, 203.579], [15.352, 38.929, 203.579], [15.352, 38.929, 203.579])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "process.py", line 322, in run
  File "process.py", line 250, in update_error
  File "process.py", line 232, in send_message
  File "multiprocessing\connection.py", line 206, in send
  File "multiprocessing\connection.py", line 280, in _send_bytes
BrokenPipeError: [WinError 232] 管道正在被关闭。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "process.py", line 329, in run
  File "process.py", line 247, in update_finished
  File "process.py", line 232, in send_message
  File "multiprocessing\connection.py", line 206, in send
  File "multiprocessing\connection.py", line 280, in _send_bytes
BrokenPipeError: [WinError 232] 管道正在被关闭。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 27, in <module>
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 52, in _freeze_support
  File "multiprocessing\spawn.py", line 116, in spawn_main
  File "multiprocessing\spawn.py", line 129, in _main
  File "multiprocessing\process.py", line 329, in _bootstrap
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by lmdu** [comment]
Fixed it in version 0.10.0.
