### ISSUE TITLE
无法正常进行对接

### ISSUE THREAD

**Issue by yangzhe1235684** [lmdu/dockey#19]
Traceback (most recent call last):
  File "MolKit\hydrogenBuilder.py", line 65, in addHydrogens
  File "MolKit\molecule.py", line 102, in __getattr__
  File "MolKit\tree.py", line 496, in __getattr__
  File "MolKit\listSet.py", line 170, in __getattr__
  File "MolKit\molecule.py", line 366, in __getattr__
AttributeError: member babel_type not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "process.py", line 328, in run
  File "process.py", line 490, in do
  File "process.py", line 289, in prepare_receptor
  File "prepare.py", line 204, in prepare_autodock_receptor
  File "AutoDockTools\MoleculePreparation.py", line 570, in __init__
  File "AutoDockTools\MoleculePreparation.py", line 140, in __init__
  File "AutoDockTools\MoleculePreparation.py", line 190, in repairMol
  File "AutoDockTools\MoleculePreparation.py", line 203, in addHydrogens
  File "MolKit\hydrogenBuilder.py", line 69, in addHydrogens
  File "PyBabel\atomTypes.py", line 141, in assignHybridization
  File "PyBabel\atomTypes.py", line 294, in valence_two
  File "PyBabel\util.py", line 55, in bond_angle
ZeroDivisionError: ('Input used:', [28.999, 41.694, 2.992], [28.999, 41.694, 2.992], [28.999, 41.694, 2.992])

**Comment by lmdu** [comment]
Please, send  the dockey project file with extension .dock to me for debug.
