### ISSUE TITLE
对接失败

### ISSUE THREAD

**Issue by Wanghanbin2468** [lmdu/dockey#24]
1. 受体蛋白：PDB_ID: 1Y5I, 处理：加氢、去水、去有机物、去除B、C链。
2. 配体Pubchem CID: 943
3. 对接结构失败
4. 显示如下：
Traceback (most recent call last):
  File "MolKit\hydrogenBuilder.py", line 65, in addHydrogens
  File "MolKit\molecule.py", line 102, in __getattr__
  File "MolKit\tree.py", line 496, in __getattr__
  File "MolKit\listSet.py", line 170, in __getattr__
  File "MolKit\molecule.py", line 366, in __getattr__
AttributeError: member babel_type not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "process.py", line 328, in run
  File "process.py", line 490, in do
  File "process.py", line 289, in prepare_receptor
  File "prepare.py", line 204, in prepare_autodock_receptor
  File "AutoDockTools\MoleculePreparation.py", line 570, in __init__
  File "AutoDockTools\MoleculePreparation.py", line 140, in __init__
  File "AutoDockTools\MoleculePreparation.py", line 190, in repairMol
  File "AutoDockTools\MoleculePreparation.py", line 203, in addHydrogens
  File "MolKit\hydrogenBuilder.py", line 69, in addHydrogens
  File "PyBabel\atomTypes.py", line 141, in assignHybridization
  File "PyBabel\atomTypes.py", line 294, in valence_two
  File "PyBabel\util.py", line 55, in bond_angle
ZeroDivisionError: ('Input used:', [-124.512, -87.645, 8.462], [-124.512, -87.645, 8.462], [-124.512, -87.645, 8.462])
请问这是对接程序的问题还是受体蛋白的问题？如何解决呢？

**Comment by lmdu** [comment]
请下载Dockey v1.0.0试一下，这个问题可以通过切换分子准备工具来解决，受体默认是用AutoDockTools，如果遇到问题，可以直接使用Openbabel试一下
