### ISSUE TITLE
Failure

### ISSUE THREAD

**Issue by crf2213** [lmdu/dockey#31]
Traceback (most recent call last):
  File "process.py", line 331, in run
  File "process.py", line 615, in do
Exception: Configuration file parse error: unknown option scoring

Correct usage:

Input:
  --receptor arg        rigid part of the receptor (PDBQT)
  --flex arg            flexible side chains, if any (PDBQT)
  --ligand arg          ligand (PDBQT)

Search space (required):
  --center_x arg        X coordinate of the center
  --center_y arg        Y coordinate of the center
  --center_z arg        Z coordinate of the center
  --size_x arg          size in the X dimension (Angstroms)
  --size_y arg          size in the Y dimension (Angstroms)
  --size_z arg          size in the Z dimension (Angstroms)

Output (optional):
  --out arg             output models (PDBQT), the default is chosen based on 
                        the ligand file name
  --log arg             optionally, write log file

Misc (optional):
  --cpu arg                 the number of CPUs to use (the default is to try to
                            detect the number of CPUs or, failing that, use 1)
  --seed arg                explicit random seed
  --exhaustiveness arg (=8) exhaustiveness of the global search (roughly 
                            proportional to time): 1+
  --num_modes arg (=9)      maximum number of binding modes to generate
  --energy_range arg (=3)   maximum energy difference between the best binding 
                            mode and the worst one displayed (kcal/mol)

Configuration file (optional):
  --config arg          the above options can be put here

Information (optional):
  --help                display usage summary
  --help_advanced       display usage summary with advanced options
  --version             display program version

**Comment by lmdu** [comment]
You should use Vina version >= 1.2.3. You can go to [https://github.com/ccsb-scripps/AutoDock-Vina/releases](https://github.com/ccsb-scripps/AutoDock-Vina/releases) to download latest version.

**Comment by crf2213** [comment]
Thanks for your adivice, I have handled this problem. what's more i try to use Dockey for Large-scale Docking, it workes well,however some receptors comeout faliures, and i don't know where the problem lies

Traceback (most recent call last):
  File "MolKit\hydrogenBuilder.py", line 65, in addHydrogens
  File "MolKit\molecule.py", line 102, in __getattr__
  File "MolKit\tree.py", line 496, in __getattr__
  File "MolKit\listSet.py", line 170, in __getattr__
  File "MolKit\molecule.py", line 366, in __getattr__
AttributeError: member babel_type not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "process.py", line 331, in run
  File "process.py", line 493, in do
  File "process.py", line 292, in prepare_receptor
  File "prepare.py", line 462, in prepare_receptor
  File "prepare.py", line 207, in prepare_autodock_receptor
  File "AutoDockTools\MoleculePreparation.py", line 570, in __init__
  File "AutoDockTools\MoleculePreparation.py", line 140, in __init__
  File "AutoDockTools\MoleculePreparation.py", line 190, in repairMol
  File "AutoDockTools\MoleculePreparation.py", line 203, in addHydrogens
  File "MolKit\hydrogenBuilder.py", line 69, in addHydrogens
  File "PyBabel\atomTypes.py", line 141, in assignHybridization
  File "PyBabel\atomTypes.py", line 294, in valence_two
  File "PyBabel\util.py", line 55, in bond_angle
ZeroDivisionError: ('Input used:', [-23.26, 1.281, 2.301], [-23.26, 1.281, 2.301], [-23.26, 1.281, 2.301])
