### ISSUE TITLE
(MacOS) AttributeError: member babel_type not found

### ISSUE THREAD

**Issue by zsemersky** [lmdu/dockey#9]
I saw another post related to this error where the solution was in Edit -> Settings -> Receptor preprocessing tab. However, on MacOS, the edit tab does not have a Settings panel, nor does any of the other panels. Attached is a screenshot. Is there a workaround to this?

Here is the error:

Traceback (most recent call last):
  File "MolKit/hydrogenBuilder.py", line 65, in addHydrogens
  File "MolKit/molecule.py", line 102, in __getattr__
  File "MolKit/tree.py", line 496, in __getattr__
  File "MolKit/listSet.py", line 170, in __getattr__
  File "MolKit/molecule.py", line 366, in __getattr__
AttributeError: member babel_type not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "process.py", line 318, in run
  File "process.py", line 335, in do
  File "process.py", line 279, in prepare_receptor
  File "prepare.py", line 204, in prepare_autodock_receptor
  File "AutoDockTools/MoleculePreparation.py", line 570, in __init__
  File "AutoDockTools/MoleculePreparation.py", line 140, in __init__
  File "AutoDockTools/MoleculePreparation.py", line 190, in repairMol
  File "AutoDockTools/MoleculePreparation.py", line 203, in addHydrogens
  File "MolKit/hydrogenBuilder.py", line 69, in addHydrogens
  File "PyBabel/atomTypes.py", line 141, in assignHybridization
  File "PyBabel/atomTypes.py", line 294, in valence_two
  File "PyBabel/util.py", line 55, in bond_angle
ZeroDivisionError: ('Input used:', [-33.236, 47.639, 26.683], [-33.236, 47.639, 26.683], [-33.236, 47.639, [26.683])
<img width="452" alt="Screenshot 2023-10-20 at 7 08 39 AM" src="https://github.com/lmdu/dockey/assets/148550604/8cc41400-2ccc-4c00-ab79-b67b779a1837">

**Comment by lmdu** [comment]
Thank you for reporting this issue. The MacOS system have removed the settings menu. I will fix it in next version.

**Comment by lmdu** [comment]
I have fixed it in version v0.10.1.  I have added a icon into toolbar for opening setting dialog.
